In [ ]:
#Распределение Пуассона
from math import exp, factorial
def P(k):
    return 3**k / factorial(k)*exp(-3)
print(1 - sum([P(k) for k in range(5)]))

In [1]:
x = {'a': 1}
y = {'b': 2}
z = {**x, **y}
z

{'a': 1, 'b': 2}

In [2]:
z1 = {x + y}
z1

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [3]:
z2 ={*x,  *y}
z2

{'a', 'b'}

In [2]:
name = {
    124: "Сергей",
    444: "Анатолий",
    952: "Николай"}
user_id = 375
print(name.get(user_id, "Уважаемый"))

Уважаемый


In [4]:
s = list(map(lambda x: x * x, (1, 2, 3, 4)))
print(s)

[1, 4, 9, 16]


In [ ]:
[3, 5]

In [ ]:
[[3], [5]]

In [2]:
(2+2+4+8)/4

4.0

In [ ]:
True + ~False

In [ ]:
True 
False
0 
1
None


In [1]:
s = map(lambda x, y: x + y, [1, 2, 3], [4, 5, 6])
print(list(s))

[5, 7, 9]


In [2]:
s = list(map(lambda x, y: x + y, [1, 2, 3], [4, 5, 6]))
print(s)

[5, 7, 9]


In [10]:
add_100 = lambda i: i+100

import numpy as np
matrix = np.array([[1, 2], [3, 4]])
vec_add_100 = np.vectorize(add_100)
vec_add_100(matrix)

array([[101, 102],
       [103, 104]])

In [11]:
add_100 = lambda i: i+100
import numpy as np
matrix = np.array([[1, 2], [3, 4]])
add_100(matrix)

array([[101, 102],
       [103, 104]])

In [15]:
def gt_100(x):
    if x > 100:
        return True
    else:
        return False
    
import numpy as np
matrix = np.array([[99, 101], [100, 102]])
gt_100 = np.vectorize(gt_100)
gt_100(matrix)

array([[False,  True],
       [False,  True]])

In [17]:
def gt_100(x):
    if x > 100:
        return True
    else:
        return False
    
import numpy as np
matrix = np.array([[99, 101], [100, 102]])
gt_100 = np.parallelize(gt_100)
gt_100(matrix)


AttributeError: module 'numpy' has no attribute 'parallelize'

In [14]:
def gt_100(x):
    if x > 100:
        return True
    else:
        return False
    
import numpy as np
matrix = np.array([[99, 101], [100, 102]])
gt_100(matrix)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [1]:
tup = (5, 7, 22, 97)
newtup = tuple(map(lambda x: x + 3, tup))
print(newtup)

(8, 10, 25, 100)


In [40]:

import numpy as np
#np.random.random(1, 10, 3)
#np.random.randint(0, 10, 3)
np.random.randint(1, 11, 3)






array([9, 8, 4])

In [109]:
tup = (5, 7, 22, 97)
newtup = tuple(map(lambda x: x + 3, tup))
print(newtup)

(8, 10, 25, 100)


In [18]:
x = 5
print([y%2 for y in range(6)][x])
t = []
for z in range(6):
    t.append(z)
    z += 1
print(t)

1
[0, 1, 2, 3, 4, 5]


In [5]:
lister = ['one', 'list', '', 'dict', '100', '50', '1 + 2']
list(filter(str.isdigit, lister))

['100', '50']

In [4]:
a = {1: "London", 3: "Berlin"}
b = {2: "New York", 3: "Moscow", 4: "Geneva"}

{**a, **b}

{1: 'London', 3: 'Moscow', 2: 'New York', 4: 'Geneva'}

In [ ]:
({1: "London", 3: "Berlin"}, {2: "New York", 3: "Moscow", 4: "Geneva"})

In [ ]:
{1: "London", 2: "New York", 3: "Berlin", 3: "Moscow", 4: "Geneva"}

In [31]:

name = '      python    '
name.rstrip()

'      python'

In [2]:
import numpy as np
vector_a = np.array([1,0,1])
vector_b = np.array([2,2,2])

vector_a @ vector_b

4

In [3]:
np.dot(vector_a, vector_b)

4

Скалярное произведение векторов можно получить через выражение  
np.dot(vector_a, vector_b), где np - библиотека numpy.
Как еще можно получить скалярное произведение векторов?

In [5]:
vector_a @ vector_b

4

In [4]:
vector_a * vector_b

array([2, 0, 2])

In [ ]:
vector_a . vector_b

In [ ]:
vector_a ** vector_b

In [ ]:
vector_a & vector_b

In [ ]:
vector_a ^ vector_b

In [ ]:
Альтернативного варианта для получения скалярного произведения нет

In [18]:
7%3 + 7%3

2

In [ ]:
1

In [13]:
list(range(3))

[0, 1, 2]

In [14]:
'a b c'.split(' ')

['a', 'b', 'c']

In [30]:
'asd'.split()

['asd']

In [3]:
import numpy as np
matrix = np.array([[1, 2], [4, 9]])

In [5]:
a, b = np.linalg.eig(matrix)
a

array([0.10102051, 9.89897949])

In [6]:
b

array([[-0.91209559, -0.21927526],
       [ 0.40997761, -0.97566304]])

In [7]:
eigenvalues, eigenvectors = np.eig(matrix)
eigenvalues

AttributeError: module 'numpy' has no attribute 'eig'

In [8]:
c, d = linalg.eig(matrix)
c

NameError: name 'linalg' is not defined

In [9]:
eigenvalues, eigenvectors = np.linalg.dot(matrix)

AttributeError: module 'numpy.linalg' has no attribute 'dot'

In [1]:
print((1, 2, 3) < (1, 2, 4))

True


In [24]:
",".join(['1', '2', '3', '4'])

'1,2,3,4'

In [1]:
print(type(type(bool(1))))

<class 'type'>


In [ ]:
<class 'bool'>

In [ ]:
<class 'int'>

In [ ]:
Будет ошибка

In [3]:
print(float('inf') * 2)

inf


In [4]:
x = float('inf')
s = x - x
print(s)

nan


In [6]:
class C():    
    def setname(self, Tom):  
        self.name = Tom  

I = C()    
I.name

AttributeError: 'C' object has no attribute 'name'

In [1]:
import numpy as np
import pandas as pd
a = pd.np.array([1, 2, 3])
b = np.array([-3, 2, 1])
print(a @ b)

4


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [6]:
import numpy as np
import pandas as pd
a = pd.np.array([1, 2, 3])
b = np.array([-3, 2, 1])
print(a @ b)

4


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [2]:
x = 5
y = '5'
print(x == y and not y == x)

False


In [ ]:
True

In [ ]:
AttributeError

In [ ]:
ValueError

In [ ]:
TypeError

In [ ]:
Ничего из вышеперечисленного

In [4]:
1 > 1 or {} or 'hello' or type('hello') is str and False

'hello'

In [6]:
2 > '1'

TypeError: '>' not supported between instances of 'int' and 'str'

In [2]:
x = [1, 2, 3, [4, 5], 6]
print(x[x[3][0]])

6


In [ ]:
1

In [ ]:
4

In [ ]:
5

In [ ]:
6

In [ ]:
IndexError

In [8]:
import datetime
today = datetime.date.today()
print(str(today))

2020-10-21


In [11]:
int("0b11111100011", 2)



2019

In [12]:
int('0b11111100100', 2) + int('-0o3744', 8)

0

In [1]:
print(r'1\nb\tc\\'[:-1])

1\nb\tc\


In [2]:
print(r'1\nb\tc' + '\\')

1\nb\tc\


In [3]:
print('1\\nb\\tc\\')

1\nb\tc\


r'....\'

In [4]:
print('1\nb\tc\')

SyntaxError: EOL while scanning string literal (<ipython-input-4-d3cd01eac379>, line 1)

In [5]:
print(r'1\nb\tc\')

SyntaxError: EOL while scanning string literal (<ipython-input-5-14fd4aad38ce>, line 1)

In [6]:
print('\n1\t2\')


1	2


In [ ]:
\n1\t2\

Нужно вывести выражение \n1\t2\.
Конструкция print('\n1\t2\') приводит к ошибке, так как если перед кавычкой стоит нечетное число слэшей, то последний экранирует кавычку, и указание строки, как raw, не помогает.
Есть три способа это сделать. Выберите вариант ниже, который не даст нужный вывод.

In [7]:
print(r'\n1\t2' + '\\')

\n1\t2\


In [8]:
print(r'\n1\t2\\'[:-1])

\n1\t2\


In [9]:
print('\\n1\\t2\\')

\n1\t2\


In [11]:
print(r'\n1\t2\\')

\n1\t2\\


In [13]:
x = [[]]*2
x[0].append(1)
x = x + x
x[-1].append(2)
print(x)

[[1, 2], [1, 2], [1, 2], [1, 2]]


In [19]:
x = [[]]*2
x

[[], []]

In [20]:
x[0].append(1)

In [21]:
x

[[1], [1]]

In [22]:
x = x + x
x

[[1], [1], [1], [1]]

In [25]:
x = [[0]]
x = x + x * 2
x[0].append(1)
print(x)

[[0, 1], [0, 1], [0, 1]]


In [ ]:
[0, 1], [0], [0]]

In [ ]:
[[0, 1], [0]]

In [ ]:
[[0, 1], [0, 1]]


In [ ]:
TypeError

In [ ]:
IndexError

In [ ]:
[[0, 1], [1], [1]]

In [ ]:
[[1], [1], [1]]

In [ ]:
[[1]]

In [5]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
a.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6]])

In [2]:
import numpy as np
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.max(b, axis=0)

array([7, 8, 9])

In [7]:
import numpy as np
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Полученная матрица:\n", b)
print(np.max(b, axis=0))

Полученная матрица:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]


In [4]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.reshape(1, -1))

[[1 2 3 4 5 6]]


In [6]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.reshape(1, -1))

[[1 2 3 4 5 6]]


In [2]:
S = '5'
S = chr(ord(S) + 1)
S

'6'

In [3]:
S = chr(ord(S) + 1)
S

'7'

In [4]:
int('5')

5

In [9]:
ord('5') - ord('2')

3

In [1]:
B = '1101'
I = 0
while B != '':
    I = I * 2 + (ord(B[0]) - ord('0'))
    B = B[1:]
print(I)

13


In [6]:
int('1101', 2)

13

In [7]:
bin(13)

'0b1101'

In [10]:
ord('5') - ord('2')

3

In [14]:
#type(ord('5') - ord('2'))

In [ ]:
'3'

In [ ]:
[3]

In [13]:
#bin(3)

In [ ]:
ord('3')

In [ ]:
51

In [ ]:
'0b11'

In [17]:
ord('5') + ord('2') == 7

False

In [18]:
ord('5')

53

In [19]:
ord('2')

50

In [20]:
type(ord('5') + ord('2'))

int

In [21]:
ord('5') + ord('2')

103

In [14]:
def bark():
    print('Good morning')
funcs = [bark, str.lower, str.capitalize]
for f in funcs:
    print(f, f('hi'))

TypeError: bark() takes 0 positional arguments but 1 was given

In [13]:
def greet(func):
    greeting = func("hello")
    print(greeting)
    
    greet(bark)

In [5]:
from functools import reduce
funcs = [str.title, lambda x: x*2]
print(reduce(lambda acc, f: f(acc), funcs, 'hello'))

HelloHello


In [ ]:
Hello hellohello

In [ ]:
hellohello
hello
Hello
None
TypeError
ValueError
AttributeError

In [22]:
class Person:
    def __init__(self, name):
        self._name = name

    @property
    def name(self):
        return self._name

person = Person('Jone')
print(Person.name.fget(person) == person.name)

True


In [1]:
a = {1, 2, 3}
b = {3, 2, 1}
print(a == b, a is b)

True False


In [ ]:
False True

In [ ]:
False False

In [ ]:
True True

In [ ]:
Посмотреть результаты

In [11]:
print(sorted([str(x) for x in range(1, 30, 5)]))

['1', '11', '16', '21', '26', '6']


In [ ]:
#['1', '11', '16', '21', '26', '6']

In [ ]:
#['1', '6', '11', '16', '21', '26']

In [8]:
c = ['1', '6', '11', '16', '21', '26']
c.reverse()
c

['26', '21', '16', '11', '6', '1']

In [ ]:
#[1, 6, 11, 16, 21, 26]

In [ ]:
None

In [ ]:
NameError

Элементы списка здесь строки, а не числа, поэтому порядок сортировки - лексикографический.

In [10]:
print([str(x) for x in range(1, 30, 5)].sort())

None


In [12]:
print(2 ^ 3 ^ 8 ^ 3 ^ 2)

8


In [16]:
print(2 ^ 3 ^ 3 ^ 2 ^ 2 ^ 4 ^ 2 ^ 4 ^ 2)

2


In [ ]:
0
1
2
3
4
7

In [15]:
a = 1; b = 2
print(eval('print(a + b, end=" ") or 0'))

3 0


In [ ]:
0
3
3 None
3 0
None 3
0 3
SyntaxError

In [40]:
import numpy as np
mat = np.array([[1], [2]])
mat.shape

(2, 1)

In [25]:
import re
sent = 'Hello, Ben! How are you doing?'
lister = filter(None, re.split("[,!?]+", sent))
print(len(list(lister)))

3


In [ ]:
1

In [ ]:
2

In [ ]:
3

In [ ]:
4

In [ ]:
5

In [ ]:
Будет ошибка

In [ ]:
Посмотреть результаты

In [ ]:
Что используется для оценки модели в машинном обучении?

In [ ]:
Исходный датасет

In [ ]:
Тренировочный датасет

In [ ]:
Тестовый датасет

In [ ]:
Ничего, так как в оценке модели нет смысла

In [ ]:
Посмотреть результаты

In [2]:
from itertools import product
a = [1, 2]
b = [3, 4]
#a = [1]
#b = [6]
try:
    print(list(product(a,b)))
except:
    print(1)
else:
    print(2)

[(1, 3), (1, 4), (2, 3), (2, 4)]
2


In [11]:
from itertools import product
a = [1, 2]
b = [3, 4]
sum(sum(product(a, b), (0, 0)))

20

In [ ]:
7

In [ ]:
10

In [ ]:
15

In [ ]:
20

In [ ]:
30

In [ ]:
Будет ошибка

In [ ]:
Посмотреть результаты

In [13]:
try:
    print('1', end=" ")
    x = 1 * 0
except:
    print('2', end=" ")
else:
    print('3', end=" ")
finally:
    print('4', end=" ")

1 2 4 

In [17]:
def f(x):
    try:
        print('1', end=" ")
        y = 1 * 0 if x % 2 else 1 / 0
    except:
        y = 0
        print('2', end=" ")
    else:
        print('3', end=" ")
    finally:
        print('4', end=" ")
    return y

print(f(1) + f(2))

1 3 4 1 2 4 0


In [ ]:
1 2 4 1 3 4 0
1 2 4 1 3 4
1 2 4 0
1 3 4 0

In [ ]:
Будет ошибка

In [ ]:
Посмотреть результаты

In [7]:
import numpy as np
mat = np.array([[1, 2], [4, 5]])
print(mat @ np.linalg.inv(mat))

[[1. 0.]
 [0. 1.]]


Пятница

In [1]:
import numpy as np
print(np.uint8(1 - 2))

255


In [ ]:
Варианты ответов:
-1
1
2
127
-128
255 - правильный
-255

In [2]:
import numpy as np
print(np.asarray([100, 200, 300]).astype(np.int8))

[100 -56  44]


In [3]:
np.int8(127), np.int8(128), np.int8(129)

(127, -128, -127)

In [4]:
import numpy as np
print(np.asarray([100, 129, 300]).astype(np.int8))

[ 100 -127   44]


In [ ]:
Варианты ответа:
[100 -56 44] - правильный
[100 56 -44]
[100 200 -44]
[100 200 300]
[-28 56 44]
[100 72 84]

In [9]:
import numpy as np
mat = np.array([[1, 2], [4, 5]])
print(round((mat @ np.linalg.inv(mat)).sum()))

2.0


In [ ]:
-1.0 
0.0
1.0
2.0
3.0
4.0


In [ ]:
Что выведет код?

In [4]:
S = 'Hello, Max!'.isalnum()
try:
    10/S
except:
    print('Buy, Max')
else:
    print('See you tomorrow')

Buy, Max


In [ ]:
Ответы

Hello, Max!
Buy, Max
See you tomorrow
ZeroDivisionError

In [ ]:
"".join(chr(i) if i % 2 else chr(i).upper() for i in range(ord('a'), ord('e')))

In [ ]:
Оветы

In [ ]:
Ответы
abcd
ABCD
AbCd
aBcD
Будет ошибка

In [5]:
False ** False + True * 2 + ([] or (True + False))

4

In [ ]:
Ответы

2
3
4
5
True
False
None
TypeError
SyntaxError
Посмотреть результаты

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
c = c * a
print(c[1])

In [ ]:
4
5
7
9
14
27

In [ ]:
Какой из классов библиотеки scikit-learn не решает задачу регрессии?
DecisionTreeRegressor
RandomForestRegressor
LinearRegression
LogisticRegression
Посмотреть результаты

In [ ]:
Правильный ответ LogisticRegression

In [ ]:
class MyList(list):
    def __getitem__(self, index):
        if type(index) is slice:
            index = slice(index.start - 1, index.stop - 1, index.step)
        elif type(index) is int:
            index -= 1
        return list.__getitem__(self, index)

l = MyList(["one", "two", "three", "four", "five", "six"])

print(l[1], l[-1], l[0], l[2:4])

In [ ]:
Ответы
two six one ['three', 'four']
one six None ['two', 'three']
one five six ['two', 'three']
one five six ['three', 'four']
one five six None
IndexError
TypeError
AttributeError

In [ ]:
Библиотека pandas
Код при обработке датафрейма df
df[df['Age'].isnull()]
-заполнит колонку 'Age' значениями Nan
-выберет и покажет строки в которых в колонке 'Age' отсутствуют значения
-вернет True, если в колонке 'Age' есть Nan 
-подсчитает число пропущенных значений в колонке 'Age'
-выдаст ошибку


In [ ]:
import pandas as pd
df = pd.DataFrame()
df['age']  = [36, 43, None]
df['name']  = ['Tom', 'Jone', 'Den']
df[df['age'].isnull()]

In [ ]:
+выберет и покажет строки в которых в колонке 'Age' отсутствуют значения

In [ ]:
Как вывести философию Python?
import this
import philosophy
print(__philosophy__)
print(__pypy__)
print()
exec('__ph__')

In [ ]:
class A:
    def __init__(self, x):
        self.x = x
    def __getattribute__(self, name):
        if name == '__add__':
            self.x *= 10
        return object.__getattribute__(self, name)
    def __add__(self, other):
        return self.x + other.x

a1 = A(2)
a2 = A(3) 
print(a1 + a2, a1.__add__(a2))

In [ ]:
5 5
23 5
5 23
23 23
NameError
RecursionError
Посмотреть результаты

In [5]:
S = 'abcdef'
print(S.islower() + S.lower().isalpha() + S.isupper())

2


In [ ]:
0
1
2
3
6
True
False
TypeError
Посмотреть результаты

In [6]:
class A:
    def __getitem__(self, i):
        return i
a = A()
a.__getitem__ = lambda i: i**2

print(a[4])

4


In [ ]:
4
8
16
None
IndexError
TypeError
Посмотреть результаты

In [ ]:
from functools import reduce
print(reduce(lambda acc, x: x * acc, [1,2,3,4], 1))

In [ ]:

0
1
10
24
TypeError

In [5]:
class A:
    x = 'hello'
    def __getitem__(self, i):
        return getattr(self.x, '__getitem__')(i) * 2
    def __getattr__(self, attr):
        return getattr(self.x, attr)
a = A()
print(a[0] + a.upper()[1:])

hhELLO


In [ ]:
HELLO
hELLO
hhello
hhELLO
HHELLO
IndexError

In [5]:
class С: pass 
c = С() 
a = type(c) == c.__class__
b = type(type(c)) is c.__class__.__class__
print(a, b)

True True


In [4]:
(type(type) is type(object)) - isinstance(type, object)

0

ответы
-1
0
1
True
False
TypeError
Посмотреть результаты

In [ ]:
isinstance(type, object) + isinstance(object, type) + (type is object)

In [ ]:
0
1
2
3
True
False
TypeError
Посмотреть результаты

In [4]:
class A: attr = 1  
class B (A): pass     
class С (A): attr = 2
class D(B, С): pass   
x = D()
print(x.attr)


2


In [ ]:
1
2
None
AttributeError
Посмотреть результаты

In [3]:
a = type([1, 2, 3]) == type(list)
b = [1, 2, 3].__class__ == list.__class__
print(a, b)

False False


In [4]:
class A: attr = 1  
class B(A): pass
class C(B): pass
class D(A): attr = 2
class E(C, D): attr = C.attr  
x = E()
print(x.attr)

1


In [ ]:
1
2
None
AttributeError
Посмотреть результаты

In [7]:
class A: pass
class B(A): pass 
class C1(A): pass 
class C2: pass
class D1(B, C1): pass
class D2(B, C2): pass

X = list(D1.__mro__)
Y = list(D2.__mro__)
print(X[3] is Y[2])

True


In [ ]:
True
False
TypeError
AttributeError
Посмотреть результаты

In [4]:
class MyList(list):
    def __getitem__(self, index):
        return super().__getitem__(index) * 2
m = MyList([1, 2])
print([m[i] + x for i, x in enumerate(m)])

[3, 6]


In [ ]:
[1, 2]
[1, 2, 1, 2]
[2, 4]
[3, 6]
TypeError
IndexError

In [36]:
class D:
    __slots__ = ['a', 'b']
d = D()
d.a = 1
f = lambda attr: getattr(d, attr, '*')
print(f('a'), f('b'), f('__dict__'))

1 * *


In [ ]:
1 1 1
1 1 *
1 * *
* * *
* 1 1
* * 1
Посмотреть результаты

In [1]:
class D:
    __slots__ = ["a", "__dict__"]
    def __init__(self):
        self.b = 2
d = D()
d.a = 1
d.c = 3
print(sorted(d.__dict__.values()))

[2, 3]


In [ ]:
[1, 2, 3]
[1, 2]
[2, 3]
[1, 3]
[1]
[2]
AttributeError

In [3]:
2 << 2

8

In [ ]:
class MyList(list):
    def __iter__(self):
        return iter(self*2)
m = MyList([1, 2, 3])
print(list(m))

In [ ]:
None
[]
[1, 2, 3]
[1, 2, 3, 1, 2, 3]
TypeError
IndexError

In [ ]:
from random import randint
num = randint(10**8, 10**20)
s = bin(num)[2:].replace('0', '\n').replace('1', '\t')
print(s.isspace())

In [ ]:
0
1
True
False
\n
\t
TypeError
Посмотреть результаты

In [ ]:
Как перезагрузить ранее импортированный модуль somemodule , если его код был изменен?
import somemodule
import importlib; importlib.reload(somemodule)   правильный ответ
somemodule.reload()
somemodule.reimport()
import somemodule with reload
reimport somemodule

In [4]:
"hello".zfill(10)

'00000hello'

In [ ]:
'0000000000hello'
'hello0000000000'
'0000000000hello0000000000'
'00000hello'
'hello00000'
'00000hello00000'

In [10]:
import numpy as np
A = np.random.randint(1, 100, size=(5, 5))
B = A.copy()
B[:, [0, -1]] = B[:, [-1, 0]]
d = lambda x: round(np.linalg.det(x))
print(d(A) + d(B))

0.0


In [ ]:
0.0
1.0
7.0
100.0
None
nan

In [7]:
A = np.random.randint(1, 100, size=(5, 5))
A

array([[32, 79, 28, 44, 17],
       [62, 57, 94, 14, 93],
       [74, 94,  6,  6, 78],
       [36, 67, 19, 55, 94],
       [58, 58, 74, 56, 95]])

//////////////////////////////////////////////

Понед

In [ ]:
1 задача

In [3]:
import numpy as np
A = np.arange(9).reshape(-1, 3)
print(np.linalg.det(A))

-2.0


In [ ]:
-2 -1 0 1 2

In [1]:
-453492 % 45681 + 453492 % 45681

45681

In [2]:
-1 % 10 + 1 % 10

10

In [5]:
from importlib import reload

reload(this)

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


<module 'this' from 'C:\\Users\\user\\Anaconda3\\lib\\this.py'>

In [ ]:
S.capitalize()
S.casefold()
S.center(width [, fill])
S.count(sub [, start [, end]])
S.encode([encoding [,errors]])
S.endswith(suffix [r start [, end]])
S.expandtabs([tabsize])
S.find(sub [, start [, end]])
S.format(fmtstr, *args, **kwargs)
S.index(sub [, start [, end]])
S.isalnum()
S.isalpha()
S.isdecimal()
S.isdigit()
S.isidentifier()
S.islower()
S.isnumeric()
S.isprintable()
S.isspace()
S.istitle()
S.isupper()
S.join(iterable)
S.ljust(width [, fill])
S.lower()
S.lstrip([chars])
S.maketrans (x [, y[, z] ] )
S.partition(sep)
S.replace(old, new [, count])
S.rfind(sub [,start [,end]])
S.rindex(sub [, start [, end]])
S.rjust(width [, fill])
S.rpartition(sep)
S.rsplit([sep[, maxsplit]])
S.rstrip([chars])
S.split([sep [,maxsplit]])
S.splitlines([keepends])
S.startswith(prefix [, start [, end]])
S.strip([chars])
S.swapcase()
S.title()
S.translate(map)
S.upper()
S.zfill(width)


In [9]:
s = "Hello, world!"
s.find("world", 5)

7

In [6]:
#влпрос уже на tocit
("Python"*3).count("Python", 0, 15)

2

Ответы
0
1
2
3
4
"Python"
Будет ошибка

In [5]:
#вопрос уже на tocit
"Hello, world!".find("world", 0, 7)

-1

In [ ]:
-1
0
1
2
6
7
None

In [ ]:
# 18 Что выведет код:

In [7]:
bool.__bases__

(int,)

In [8]:
isinstance(True, bool)

True

In [12]:
print(isinstance(True, int), isinstance(True, bool))

True True


In [5]:
"".join(chr(x) for x in range(67, 80))

'CDEFGHIJKLMNO'

In [26]:
#dict((ord(x), "x") for x in ['l', 'e', 'h'])

{108: 'x', 101: 'x', 104: 'x'}

In [1]:
"hello".translate(dict((ord(x), "x") for x in ['l', 'e', 'h']))

'xxxxo'

In [1]:
def reducer_func(el_prev, el):
        # el_prev — предшествующий элемент
        # el — текущий элемент
        return el_prev + el
from functools import reduce
reduce(reducer_func, [1, 2, 3])

6

In [ ]:
Задача

In [32]:
def f(acc, x):
    print('acc = ', acc)
    print('x = ', x)
    print('------------')
    return acc * x
x = [1,2,3,4]
acc = 1
print(reduce(f, [1,2,3,4], 1))

acc =  1
x =  1
------------
acc =  1
x =  2
------------
acc =  2
x =  3
------------
acc =  6
x =  4
------------
24


In [ ]:
/////////////////

Решение системы уравнений

In [5]:
import numpy as np
A = np.array([[1, 2, 3], [1, 3, 1], [2, -5, 5]])
b = np.array([9, 6, 17])

In [6]:
(np.linalg.inv(A) @ b.T)

array([ 4.68421053, -0.05263158,  1.47368421])

In [7]:
(np.linalg.inv(A) @ b.T)*19

array([89., -1., 28.])

In [2]:
d = {}
d[(2, 3)] = "a", "b"
d

{(2, 3): ('a', 'b')}

In [3]:
5, 7

(5, 7)

In [4]:
(6, 7)

(6, 7)

In [5]:
"a", "b"

('a', 'b')

In [6]:
2, 3

(2, 3)

In [ ]:
d(*d[2, 3])

In [8]:
d = {}
x1 = d.get("x", 1)
x1

1

In [9]:
d

{}

In [11]:
x2 = d.setdefault('x', 2)
x2

2

In [12]:
d

{'x': 2}

In [13]:
x3 = d.get("x", 3)
x3

2

In [14]:
d1 = {'x': 2}
d2 = {}
d1.setdefault("x", 1)
d2.setdefault("x", 2)
print(d1 == d2)

True


In [16]:
d = {"a": [1], "b": 2}
d2 = d.copy()
d2["a"] += [2]
d2

{'a': [1, 2], 'b': 2}

In [17]:
d2["b"] += 3
d2

{'a': [1, 2], 'b': 5}

In [20]:
sum(d["a"])

3

In [21]:
d["b"]

2

In [23]:
sum([1, 2])

3

In [ ]:
print(sum(d["a"]) + d["b"])

In [24]:
from copy import deepcopy
d = {"a": [1], "b": 2}
d2 = deepcopy(d)
d2["a"] += [2]
d2["b"] += 3
d

{'a': [1], 'b': 2}

In [ ]:

print(sum(d["a"]) + d["b"])

In [26]:
d1 = dict.fromkeys(('a', 'b'), 1)
d2 = dict(zip(['c', 'd'], [2, 3]))
d1.update(d2)
d1

{'a': 1, 'b': 1, 'c': 2, 'd': 3}

In [27]:
print(sum(d1.values()))

7


In [5]:
import datetime
datetime.datetime.strptime("21.11.2017", %d.%m.%Y)

SyntaxError: invalid syntax (<ipython-input-5-26723fb4f3d9>, line 2)

In [6]:
from datetime import datetime

date_string = "21 June, 2018"

print("date_string =", date_string)
print("type of date_string =", type(date_string))

date_object = datetime.strptime(date_string, "%d %B, %Y")

print("date_object =", date_object)
print("type of date_object =", type(date_object))

date_string = 21 June, 2018
type of date_string = <class 'str'>
date_object = 2018-06-21 00:00:00
type of date_object = <class 'datetime.datetime'>


In [11]:
from datetime import datetime

In [14]:
d1 = datetime(2021, 10, 7)
d2 = datetime(2020, 11, 12)

In [13]:
d1 = datetime.datetime(2021, 10, 7)

AttributeError: type object 'datetime.datetime' has no attribute 'datetime'

In [2]:
'' and 'world'


''