In [2]:
a = [1, 5, 7]
b = [2, 4, 6]
c = a.extend(b)
print(c)

None


In [5]:
class A:
    def __init__(a, b, c):
        #print(b)
        print(a, b, c)
A(8,3)

<__main__.A object at 0x00000112D7DD49D0> 8 3


In [6]:
x = 'python'
print(x.zfill(10))

0000python


In [7]:
list1 = [1, 2, 3, 3, 2, 4, 6, '6']
print(len(set(list1)))

6


In [8]:
print(type(int))

<class 'type'>


In [9]:
def value(a,b):
    return a[:b]
print(value("Python", 2))

Py


In [10]:
def value(a,b):
    return a[:b]
print(value("Python", 2))

Py


In [11]:
a = 5,
b = 6, 7
c = a + b
print(c)

(5, 6, 7)


In [15]:
x = 2
y = 3
x = y

y = x * 2
print(y/x)

2.0


In [16]:
a = [0, 1, 0]
b = [1, 1, 0]
s = 0
for x in (a, b, a):
    s += x.count(1)
print(s)

4


In [17]:
x_1 = [15, "python", 12, 13, 14]
x_2 = x_1
x_1[2] = 99
print(x_2[2])

99


In [18]:
a = 3
def f(*nums):
    return sum(nums)
print(f(a, a**a, a*4))

42


In [19]:
x = "python"
try: 
    print(x.find('p'))
    print(x.find('t'))
    print(x.find('i'))
    print(x.find('d'))
except ValueError:
    pass
except IndexError:
    print(len(x))

0
2
-1
-1


In [20]:
num = []
for i in range(5):
    num.append(i)
sum_num = sum(num)
if sum_num % 2 != 0:
    print("Yes")

In [21]:
string = "edakrak"
list = range(6)
if type(list) == list:
    print(string[::2], string[1::2])
else:
    print(string[::-1])

karkade


In [22]:
x1 = (1, 2, 3)
x2 = ('a', 'b', 'c')
print(tuple(zip(x1, x2))[1][0])

2


In [ ]:
74 проверен

In [3]:
password = 'password'
adding = [х + у for х in '0123456789' for у in '0123456789']
count = 0
for a in adding:
    password = password + a
    count += 1
print(count, password[-3:])

100 899


In [1]:
x = ['a', 'b', 'c']
print('y'.join(x))

aybyc


In [2]:
x = 2
y = 3
x = y
y = x * 2
print(y/x)

2.0


In [3]:
x_1 = [15, "python", 12, 13, 14]
x_2 = x_1
x_1[2] = 99
print(x_2[2])

99


In [4]:
a = 3
def f(*nums):
    return sum(nums)
print(f(a, a**a, a*4))

42


In [5]:
3+27+12

42

In [7]:
x = "python"
try: 
    print(x.find('p'), end=' ')
    print(x.find('t'), end=' ')
    print(x.find('i'), end=' ')
    print(x.find('d'))
except ValueError:
    pass
except IndexError:
    print(len(x))

0 2 -1 -1


In [8]:
num = []
for i in range(5):
    num.append(i)
sum_num = sum(num)
if sum_num % 2 != 0:
    print("Yes")

In [10]:
string = "edakrak"
my_list = range(6)
if type(my_list) == list:
    print(string[::2], string[1::2])
else:
    print(string[::-1])

karkade


In [11]:
x1 = (1, 2, 3)
x2 = ('a', 'b', 'c')
print(tuple(zip(x1, x2))[1][0])

2


In [1]:
from collections import defaultdict
d = defaultdict(list)
d['a'].append(1)
d['a'].append(2)
d['b'].append(3)
sum((len(d['a']*3), len(d['b'])*5))

11

In [5]:
a = (1, 'foo')
b = (2, 'bar')
c = (2, 'b')
print(a < b, b < c)

True False


In [6]:
"bar"<"z"

True

In [8]:
"bar"<"afds"

False

In [1]:
from heapq import heappush, heappop
h = []
heappush(h, (5, 'a'))
heappush(h, (7, 'b'))
heappush(h, (3, 'c'))
print(heappop(h)[1])

c


In [ ]:
почему С, если индекс не 0?

In [ ]:
heappop возвращает и удаляет из кучи наименьший элемент среди помещенных туда кортежей.
Кортежи сравниваются по первому элементу, если они все различны, поэтому наименьший элемент будет (3, 'c').
Далее у кортежей берем индекс [1] и получаем с.


In [1]:
d1 = {"x": 1, "y": 2}
d2 = {"y": 2, "z": 3}
print(d1.values() - d2.values())

TypeError: unsupported operand type(s) for -: 'dict_values' and 'dict_values'

In [2]:
d1 = {"x": 1, "y": 2}
d2 = {"y": 2, "z": 3}
print(*(d1.items() - d2.items()))

('x', 1)


In [10]:
a = slice(-1200, 1100, -1)
s = "abcdef"
print(len(s[a]))

0


In [11]:
"abcde"[-10:10:-1]


''

In [ ]:
В задаче создается срез, как отдельный объект. Работает аналогично такому более простому примеру:
"abcde"[-10:10:-1]
Первый аргумент - начальный индекс (если он отрицательный, то это означает позицию смещения от конца влево, то есть -1 - последний, -2 - предпоследний и т.д.).
Второй аргумент - конечный индекс (не включая).
Третий - шаг.
Индексы могут выходить за пределы последовательности, просто там ничего нет.
Если шаг отрицательный, значит нужно идти в обратную сторону - от конца.
В нашем случае, хотя интервал между индексами и покрывает строку, шаг направлен от конца к началу, поэтому и получаем пустую строку. Чтобы была не пустота, надо поменять индексы начала и конца местами.
>>> "abcde"[-10:10:-1]
''
>>> "abcde"[10:-10:-1]
'edcba'
>>> "abcde"[-10:10:1]
'abcde'

In [1]:
from collections import namedtuple
A = namedtuple('A', ['x', 'y'])
a = A('A', ['1', '2'])
a.x = 3
print(a.x)

AttributeError: can't set attribute

In [2]:
from collections import namedtuple
A = namedtuple('A', ['x', 'y'])
a = A('A', ['1', '2'])
a

A(x='A', y=['1', '2'])

In [1]:
from collections import ChainMap
d1 = {'x': 1, 'z': 10}
d2 = {'y': 2, 'z': 20}
d3 = {**d1, **d2}
d4 = ChainMap(d1, d2)
s1 = d3['x'] + d3['y'] + d3['z']
s2 = d4['x'] + d4['y'] + d4['z']
print(s1, s2)

23 13


In [2]:
d3

{'x': 1, 'z': 20, 'y': 2}

In [3]:
d4

ChainMap({'x': 1, 'z': 10}, {'y': 2, 'z': 20})

In [6]:
d4['z']

10

In [7]:
d3['z']

20

In [13]:
from collections import ChainMap
a = {'x': 1, 'z': 3 }
b = {'y': 2, 'z': 4 }
c = ChainMap(a,b)
c['z'] = 10
c['w'] = 40
del c['x']
print(sum(a.values()), sum(b.values()))

50 6


In [14]:
c

ChainMap({'z': 10, 'w': 40}, {'y': 2, 'z': 4})

In [15]:
del c['y']

KeyError: "Key not found in the first mapping: 'y'"

In [16]:
a

{'z': 10, 'w': 40}

In [17]:
b

{'y': 2, 'z': 4}

In [18]:
from operator import itemgetter
ds = [{"x": 1}, {"x": 2, "y": 3}]
min1 = min(ds, key=itemgetter('x'))
min2 = min(i['x'] for i in ds)
print(min1 == min2)

False


In [19]:
min1

{'x': 1}

In [20]:
min2

1

In [21]:
d = {"x": 1, "y": 2}
print(itemgetter("x")(d))

1


In [24]:
s1 = {x for x in range(10**6)}
s2 = [x for x in range(10**6)]
s3 = (x for x in range(10**6))
f = lambda x: x.__sizeof__()
print(f(s1), f(s2), f(s3))

33554632 8697440 96


In [37]:
s1 = {x for x in range(10**8)}
s2 = [x for x in range(10**8)]
s3 = (x for x in range(10**8))
f = lambda x: x.__sizeof__()
print(f(s1), f(s2), f(s3))

4294967496 859724448 96


In [34]:
from timeit import timeit
timeit(lambda: sum({x for x in range(10**8)}), number=1)

9.535813199999666

In [35]:
timeit(lambda: sum([x for x in range(10**8)]), number=1)

7.5633106000000225

In [36]:
timeit(lambda: sum(x for x in range(10**8)), number=1)

6.57746969999971

In [ ]:
s1 = {x for x in range(10**6)}
s2 = [x for x in range(10**6)]
s3 = (x for x in range(10**6))
f = timeit(lambda: sum({x for x in range(10**6)}), number=1)
print(f(s1), f(s2), f(s3))

In [49]:
from timeit import timeit
timeit(lambda: {x for x in range(10**8)}, number=1)

17.832998599999883

In [50]:
timeit(lambda: [x for x in range(10**8)], number=1)

5.65552469999966

In [51]:
timeit(lambda: (x for x in range(10**8)), number=1)

3.999999989900971e-06

In [53]:
from timeit import timeit
# суммирование
print(timeit(lambda: sum({x for x in range(10**8)}), number=1))
print(timeit(lambda: sum([x for x in range(10**8)]), number=1))
print(timeit(lambda: sum(x for x in range(10**8)), number=1))
# создание объектов
print(timeit(lambda: {x for x in range(10**8)}, number=1))
print(timeit(lambda: [x for x in range(10**8)], number=1))
print(timeit(lambda: (x for x in range(10**8)), number=1))

9.0308914000002
7.586603200000354
6.754627199999959
6.3595211000001655
5.63016239999979
3.600000127335079e-06


In [1]:
text = 'ABC'
x = text.ljust(5, '*').rstrip('*').rjust(4, '*')
print(x)

*ABC


In [1]:
data = [[7,1], [10,0], [0, 6], [1, 4], [5,3], [9,9], [2,1], [4,4], [6,8]]

In [2]:
import random
def generate_centroids(k, data):
    return random.sample(data, k)

In [3]:
generate_centroids(3, data)

[[1, 4], [7, 1], [2, 1]]

In [1]:
import numpy as np
basket = np.array([[1, 1, 1, 1], [1, 1, 1, 0]])
co_purchases = np.sum(np.all(basket[:,2:], axis = 1)) / basket.shape[0]
print(co_purchases)

0.5


In [2]:
basket.shape[0]

2

In [3]:
basket.shape

(2, 4)

In [5]:
np.sum(np.all(basket[:,2:], axis = 1))

1

In [6]:
np.all(basket[:,2:], axis = 1)

array([ True, False])

In [7]:
basket[:,2:]

array([[1, 1],
       [1, 0]])

В числителе:
Когда мы берем срез basket[:,2:], то получаем (поскольку берем все строки, начиная от второго столбца)
array([[1, 1],
       [1, 0]])
Функция all() библиотеки NumPy проверяет, все ли значения в заданном массиве NumPy равны True (1 трактуется как True). В этом случае эта функция возвращает True. В противном случае она возвращает False. При указании аргумента axis функция all() делает то же самое, но по заданной оси. Т е [1, 1] даст True, а [1, 0] даст False. Суммирование дает 1 (True + False = 1).
В знаменателе:
basket.shape равен (2, 4). Мы берем только первое значение из кортежа, т е 2.
В итоге в числителе 1, в знаменателе 2. 

In [3]:
x = 1
def f():
    def g():
        nonlocal x 
        print(x)
        x += 1
    return g
g = f()
x = g()
print(x)

SyntaxError: no binding for nonlocal 'x' found (<ipython-input-3-c532a9d37420>, line 4)

In [7]:
x = 1
def f():
    def g():
        nonlocal x 
        print(x)
        x += 1
    return g
g = f()
g()


SyntaxError: no binding for nonlocal 'x' found (<ipython-input-7-ce2bbe3ef2f4>, line 4)